// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZdlel-U2tZHGz6i09wB9B8Q3pZbqNQV4',
    appId: '1:168913452969:web:2ffe40614b04ed0a1cceb8',
    messagingSenderId: '168913452969',
    projectId: 'mon-projet-33c16',
    authDomain: 'mon-projet-33c16.firebaseapp.com',
    storageBucket: 'mon-projet-33c16.firebasestorage.app',
    measurementId: 'G-B4DEFV7FL1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbVQJinfKWonN-re53_HdQhnLd16sm6dE',
    appId: '1:168913452969:android:d53b293ba9a1c4711cceb8',
    messagingSenderId: '168913452969',
    projectId: 'mon-projet-33c16',
    storageBucket: 'mon-projet-33c16.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZdlel-U2tZHGz6i09wB9B8Q3pZbqNQV4',
    appId: '1:168913452969:web:975f030e782018c81cceb8',
    messagingSenderId: '168913452969',
    projectId: 'mon-projet-33c16',
    authDomain: 'mon-projet-33c16.firebaseapp.com',
    storageBucket: 'mon-projet-33c16.firebasestorage.app',
    measurementId: 'G-M3ESEM1R97',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBixD6zz3up6UCf-Gu9b2Vu3LW3M3AjlXA',
    appId: '1:168913452969:ios:e813935f38699b781cceb8',
    messagingSenderId: '168913452969',
    projectId: 'mon-projet-33c16',
    storageBucket: 'mon-projet-33c16.firebasestorage.app',
    iosBundleId: 'com.example.monProjet',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBixD6zz3up6UCf-Gu9b2Vu3LW3M3AjlXA',
    appId: '1:168913452969:ios:e813935f38699b781cceb8',
    messagingSenderId: '168913452969',
    projectId: 'mon-projet-33c16',
    storageBucket: 'mon-projet-33c16.firebasestorage.app',
    iosBundleId: 'com.example.monProjet',
  );

}